FX2/WebGBFXT/Areas/Consultant/Controllers/PlanController.cs
#region

using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using BaseDBFX.Base;
using BaseDBFX.Table;
using Finflaex.Support.Attributes;
using Finflaex.Support.MVC.Atributes;
using Finflaex.Support.Reflection;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using WebGBFXT.Areas.Organization.Models;
using Finflaex.Support.MVC.Models;

#endregion

namespace WebGBFXT.Areas.Consultant.Controllers
{
    /// <summary>
    /// План встреч
    /// </summary>
    [NoCache]
    public class PlanController : Controller
    {
        /// <summary>
        /// Получение представления
        /// </summary>
        /// <param name="recordID"></param>
        /// <returns></returns>
        [Roles(dbroles.admin, dbroles.consultant)]
        public async Task<ActionResult> Index(Guid? recordID) 
            => await this.func(gb=>
        {
            gb.GuidValue = new MainValue
            {
                id = recordID ?? Guid.Empty
            };
            return View(gb);
        });

        /// <summary>
        /// Получение списка событий
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Post)]
        [Roles(dbroles.admin, dbroles.consultant)]
        public async Task<ActionResult> Read(
            [DataSourceRequest] DataSourceRequest request)
            => await this.func(gb =>
            {
                var db = gb.db;

                var cities = new[]
                {
                    Guid.Parse("8DEA00E3-9AAB-4D8E-887C-EF2AAA546456"), // новосибирск
                    Guid.Parse("7B6DE6A5-86D0-4735-B11A-499081111AF8"), // владивосток
                    Guid.Parse("7DFA745E-AA19-4688-B121-B655C11E482F"), // краснодар
                    Guid.Parse("0C5B2444-70A0-4932-980C-B4DC0D3F02B5"), // москва
                    Guid.Parse("555E7D61-D9A7-4BA6-9770-6CAA8198C483"), // нижний новгород
                    Guid.Parse("C2DEB16A-0330-4F05-821F-1D09C93331E6"), // санкт петербург
                    Guid.Parse("C1CFE4B9-F7C2-423C-ABFA-6ED1C05A15C5"), // ростов на дону
                    Guid.Parse("2763C110-CB8B-416A-9DAC-AD28A55B4402") // екатеринбург
                };

                var query =
                    from user in db.Logins
                    where user.ID == db.AuthorID
                    from task in user.Events
                    where task.Type == EventType.meeting
                          || task.Type == EventType.meetingConfirm || task.Type == EventType.meetingClose ||
                          task.Type == EventType.meetingEvent
                    //select new
                    //{
                    //    task,
                    //    task.Organization
                    //}
                    select new
                    {
                        main = task
                            .Organization
                            .Address
                            .Select(v => v.ID)
                            .Any(v => cities.Contains(v)),

                        task.Description,
                        task.ID,
                        task.Type,
                        task.Start,
                        task.End,
                        OrganizationID = task.OrgID,
                        task.RecordID,
                        OrganizationName = task.Organization.ShortName ?? task.Organization.FullName,
                        Notify = DbFunctions.TruncateTime(task.Notify) != DbFunctions.TruncateTime(task.Start),
                        NotifyTime = task.Notify ?? task.Start,
                        task.NotifyConsultant,
                        Address = from adr in task.Organization.Address
                        where adr.Type < AddressType.street
                        orderby adr.Type
                        select new
                        {
                            adr.Name,
                            adr.Suffix
                        },
                        Accaunts = (from e in task.Organization.Events
                            where e.Type == EventType.progress
                            where !e.Closed
                            where e.Start < gb.Now
                            where e.End > gb.Now
                            select e.Users)
                        .SelectMany(v => v)
                        .Distinct()
                        .Select(acc => new
                        {
                            acc.ID,
                            acc.Caption
                        })
                    };

                //return query
                //    .AsEnumerable()
                //    .Select(v => new SchedullerModel
                //    {
                //        ID = v.task.ID.ToString("N"),
                //        Description = v.task.Description.HtmlDecode().FromHtml(),
                //        Title = v.task.Type.AtValue(),
                //        RecordID = v.task.RecordID.Value.ToString("N"),
                //        ResID = (int)v.task.Type,
                //        _Start = v.task.Start,
                //        IsAllDay = v.task.IsAllDay,
                //        OrgName = v.Organization.ShortName
                //            .retIfNullOrWhiteSpace(v.Organization.FullName)
                //            .retIfNullOrWhiteSpace("не указано"),
                //        Notify = v.task.Notify?.Date != v.task.Start?.Date,
                //        OrganizationID = v.task.OrgID.Value.ToString("N"),
                //        Confirm = v.task.Start < db.Now && v.task.Type != EventType.meetingClose,
                //    })
                //    .Select(v =>
                //    {
                //        v.Start = v._Start.ToTZDateTime(gb.TimeZone);
                //        if (v.Start.Hour < 8)
                //        {
                //            v.Start =  v.Start.Date.AddHours(8);
                //            v.End = v.Start.AddHours(3);
                //        }
                //        else
                //        {
                //            v.End = v.Start.AddHours(3);
                //        }
                //        return v;
                //    })
                //    .ToDataSourceResult(request)
                //    .ToJsonResult();

                return query
                    .AsEnumerable()
                    .Select(v => new SchedullerModel
                    {
                        Description = v.Description.HtmlDecode().FromHtml(),
                        ID = v.ID.ToString(),
                        Title = v.Type.AtValue(),
                        //ResID = (int)v.Type,
                        ResID = v.main ? 100 + (int) v.Type : (int) v.Type,
                        Start = v.Start.ToTZDateTime(gb.TimeZone),
                        End = (v.End ?? v.Start?.AddHours(3)).ToTZDateTime(gb.TimeZone),
                        OrganizationID = v.OrganizationID.ToString(),
                        IsAllDay = false,
                        RecordID = v.RecordID.ToString(),
                        OrgName = v.OrganizationName,
                        Accaunts = v.Accaunts.Select(a => a.ID.ToString("N")).ToArray(),
                        AccauntNames = v.Accaunts.Select(a => a.Caption).Join(", "),
                        Confirm = v.Type == EventType.meetingConfirm || v.Type == EventType.meetingClose,
                        Region = v.Address.Select(a => $"{a.Name} {a.Suffix}").Join(", ")
                    })
                    .ToDataSourceResult(request)
                    .ToJsonResult();
            });

        /// <summary>
        /// Обновление события
        /// </summary>
        /// <param name="request"></param>
        /// <param name="model">событие</param>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Post)]
        [Roles(dbroles.admin, dbroles.@operator)]
        [ValidateInput(false)]
        public async Task<ActionResult> Update(
            [DataSourceRequest] DataSourceRequest request,
            SchedullerIndexModel model)
            => await this.func(gb =>
            {
                if (model.End < model.Start)
                    model.End = model.Start.AddHours(3);

                gdb.set_meeting(
                    gb.db,
                    model.ID,
                    model.Start,
                    model.End,
                    model.NotifyTime,
                    model.Description.FromHtml(),
                    model.NotifyConsultant,
                    model.Notify);

                return model
                    .InArray()
                    .ToDataSourceResult(request)
                    .ToJsonResult();
            });

        /// <summary>
        /// Удаление события
        /// </summary>
        /// <param name="request"></param>
        /// <param name="model">событие</param>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Post)]
        [Roles(dbroles.admin, dbroles.@operator)]
        public async Task<ActionResult> Destroy(
            [DataSourceRequest] DataSourceRequest request,
            SchedullerIndexModel model)
            => await this.json(gb =>
            {
                gb.db.Events.Find(model.ID).ActionIfNotNull(task =>
                {
                    gb.db.Delete(task);
                    gb.db.Commit();
                });

                return model
                    .InArray()
                    .ToDataSourceResult(request);
            });
    }
}

FX2/WebGBFXT/Areas/Operator/Controllers/PlanController.cs
#region

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using BaseDBFX.Base;
using BaseDBFX.Models;
using BaseDBFX.Table;
using Finflaex.Support.Attributes;
using Finflaex.Support.MVC.Atributes;
using Finflaex.Support.Reflection;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using WebGBFXT.Areas.Operator.Models;

#endregion

namespace WebGBFXT.Areas.Operator.Controllers
{
    /// <summary>
    /// План обзвона
    /// </summary>
    [NoCache]
    [Roles]
    public class PlanController : Controller
    {
        /// <summary>
        /// Получение представления
        /// </summary>
        /// <returns></returns>
        [Roles(dbroles.admin, dbroles.@operator)]
        public async Task<ActionResult> Index() => await this.func(View);

        /// <summary>
        /// Чтение списка событий
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [Roles(dbroles.admin, dbroles.@operator)]
        public async Task<ActionResult> Read(
            [DataSourceRequest] DataSourceRequest request)
            => await this.json(gb =>
            {
                var db = gb.db;
                db.Database.CommandTimeout = 180;

                var tz = db.Logins.Find(gb.AuthorGuid)?.TimeZone ?? 0;

                var cfg = (
                              from user in db.Logins
                              where user.ID == db.AuthorID
                              from file in user.Files
                              where file.Type == TypeFile.Config
                              where file.Name == Login.Configs.OperatorPlanConfig
                              select file)
                          .FirstOrDefault()
                          ?
                          .Raw.AsObject<OperatorPlanConfig>()
                          ?? new OperatorPlanConfig
                          {
                              Accaunt = db.AuthorID,
                              Types = new List<EventType>(),
                              Start = DateTime.Now,
                              End = DateTime.Now
                          };

                var start = cfg.Start.Date.ToTZDateTimeOffset(gb.TimeZone);
                var end = cfg.End.Date.AddDays(1).AddMilliseconds(-1).ToTZDateTimeOffset(gb.TimeZone);

                var admin_roles = new[]
                {
                    dbroles.admin,
                    dbroles.developer
                };

                if (!cfg.Types.Any())
                    cfg.Types = new[]
                    {
                        EventType.unknown,
                        EventType.callUp,
                        EventType.callTransfer,
                        EventType.meetingRate,
                        EventType.meetingEvent,
                        EventType.meeting,
                        EventType.callSeminar
                    };

                return (
                        from author in db.Logins
                        where author.ID == db.AuthorID
                        let manager = author.Roles.Any(v => v.Key == dbroles.manager)
                        let consultant = author.Roles.Any(v => v.Key == dbroles.consultant)
                        let admin = author.Roles.Select(v => v.Key).Intersect(admin_roles).Any()
                        let filter = admin || manager && !consultant
                        from user in db.Logins
                        where filter ? cfg.Accaunt == user.ID : user.ID == db.AuthorID
                        from task in user.Events
                        where cfg.Types.Contains(task.Type)
                        where task.Closed == false
                        where task.Start != null
                        where (task.Notify ?? task.Start) >= start
                        where (task.Notify ?? task.Start) <= end
                        where
                        task.NotifyConsultant && user.Roles.Select(v => v.Key).Contains(dbroles.consultant)
                        ||
                        !task.NotifyConsultant

                        // иванкова 15.08.2017 14:46
                        // where task.Organization.CloseInfo == null

                        select new
                        {
                            Name = task.Organization.ShortName ?? task.Organization.FullName,
                            task.Organization.ID,
                            EventID = task.ID,
                            task.Type,
                            Date = task.Notify ?? task.Start,
                            Address = task.Organization.Address
                                          .Where(v => v.Type == AddressType.region)
                                          .Select(v => v.Name)
                                          .FirstOrDefault()
                                      ?? task.Organization.FormatAddress
                                      ?? task.Organization.RawAddress,
                            task.Description
                        })
                    .AsEnumerable()
                    .Select(v => new PlanOrgTableItem
                    {
                        Name = v.Name,
                        ID = v.ID,
                        EventID = v.EventID,
                        Type = v.Type,
                        Date = v.Date.ConvertTimeZone(tz)?.ToString("dd MMMM yyyy"),
                        Time = v.Date.ConvertTimeZone(tz)?.ToString("HH:mm"),
                        //DateTime = v.Date.ConvertTimeZone(tz)?.DateTime,
                        DateTimeFilter = v.Date.ConvertTimeZone(tz)?.DateTime.Date,
                        Address = v.Address,
                        Description = v.Description.HtmlDecode().FromHtml()
                    })
                    .OrderBy(v => v.DateTimeFilter)
                    .ThenBy(v => v.Time)
                    .ToDataSourceResult(request, item =>
                    {
                        item.TypeString = item.Type.AtValue();
                        return item;
                    });
            });

        /// <summary>
        /// Сохранение пользовательских настроек
        /// </summary>
        /// <param name="cfg">настройки</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> SaveConfig(
            OperatorPlanConfig cfg)
            => await this.act(gb =>
            {
                var query =
                    from user in gb.db.Logins
                    where user.ID == gb.AuthorGuid
                    select new
                    {
                        user,
                        file = user.Files
                            .Where(file => file.Type == TypeFile.Config)
                            .FirstOrDefault(file => file.Name == Login.Configs.OperatorPlanConfig)
                    };

                var read = query.First();

                if (read.file == null)
                    read.user.Files.Add(new RawFile
                    {
                        Raw = cfg.AsBytes(),
                        Type = TypeFile.Config,
                        Name = Login.Configs.OperatorPlanConfig
                    });
                else
                    read.file.Raw = cfg.AsBytes();
                gb.Save();
            });
    }
}

FX2/WebGBFXT/Areas/GlobalEvents/Views/Plan/Calendar.cshtml
@using Kendo.Mvc.UI
@using WebGBFXT.Areas.Organization.Models
@model Finflaex.Support.MVC.Models.MainValue

@{
    ViewBag.Title = Model.value;
    Layout = "~/Views/Shared/_OneIndex.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2>@ViewBag.Title</h2>
    </div>
</div>

<div class="wrapper wrapper-content">
    <div class="animated fadeIn">
        @(Html.Kendo().Scheduler<SchedullerTripModel>().Name("Scheduler")
              .AllDaySlot(false)
              .StartTime(DateTime.Today.AddHours(8))
              .Views(views =>
              {
                  views.DayView(v => { v.Title("День"); });
                  views.WorkWeekView(v => { v.Title("Рабочая неделя").Selected(true); });
                  views.MonthView(v => { v.Title("Месяц"); });
              }).EventTemplateId("SchedullerTemplate")
              //.Editable(v => { v.TemplateName("SchedullerTripEdit"); })
              .Editable(false)
              .Resources(resource =>
              {
                  resource.Add(m => m.NotEdit)
                      .Title("Owner")
                      .DataTextField("Text")
                      .DataValueField("Value")
                      .DataColorField("Color")
                      .BindTo(new[]
                      {
                          //new {Text = "Alex", Value = false, Color = "#f8a398"},
                          new {Text = "Bob", Value = true, Color = "#51a0ed"},
                          new {Text = "Charlie", Value = false, Color = "#56ca85"}
                      });
              }).DataSource(d => d
                  .Model(m => { m.Id(f => f.ID); })
                  .Read(a =>
                  {
                      a.Url(Url.Action("ReadTrip", "Plan", new
                      {
                          area = "GlobalEvents",
                          eventid = Model.id
                      }));
                  })
              ))

        <script id="SchedullerTemplate" type="text/x-kendo-template">
                <strong class="block">#:OrgName#</strong>
                <small>#:title#</small>
                <p>#=description#</p>
            </script>
    </div>
</div>

FX2/WebGBFXT/Areas/GlobalEvents/Views/Plan/Index.cshtml
@using BaseDBFX.Base
@using Finflaex.Support.Reflection
@using Finflaex.Support.Telerik
@using Kendo.Mvc.UI
@using WebGBFXT.Areas.GlobalEvents.Controllers
@model dynamic

@{
    ViewBag.Title = "Мероприятия";
    Layout = "~/Views/Shared/_OneIndex.cshtml";
}

<script id="templateCaptionEvent" type="text/x-kendo-template">
    <h3>#: Caption #</h3>
    <p>#= Comment #</p>
</script>

<script id="templateButtonEvent" type="text/x-kendo-template">
    <a class='btn btn-sm btn-default' href='Plan/Table?id=#:ID#'><i class='fa fa-list'></i></a>
    <a class='btn btn-sm btn-default' href='Plan/Calendar?id=#:ID#'><i class='fa fa-calendar'></i></a>
</script>


<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2>@ViewBag.Title</h2>
    </div>
</div>

<div class="wrapper wrapper-content">
    <div class="animated fadeIn">
        @if (Html.Author().Verificate(dbroles.consultant))
        {
            <div class="form-group">
                <div class="checkbox">
                    <label><input type="checkbox" checked="checked" id="allView">Показать остальные подразделения</label>
                </div>
            </div>
            <script>
                $("#allView").change(function() {
                    $("#PlanOrgTable").data("kendoGrid").dataSource.read();
                });

                function GridReadData() {
                    return {
                        allView: $('#allView').is(':checked')
                    };
                }
            </script>
        }
        else
        {
            <script>
                function GridReadData() {
                    return {
                        allView: false
                    };
                }
            </script>
        }
        @(Html.Kendo().Grid<PlanController.TableEventModel>().Name("PlanOrgTable").Columns(columns =>
          {
              columns
                  .Bound(v => v.Caption)
                  .ClientTemplate("#=" + "templateCaptionEvent".jsKendoTemplate() + "#")
                  .Title("Мероприятие");
              columns
                  .Bound(v => v.Departament)
                  .Title("Подразделение")
                  .Width(150);
              columns.Bound(v => v.Start)
                  .Title("Начало")
                  .Format("{0:dd.MM.yyyy HH:mm}")
                  .Width(120);
              columns.Bound(v => v.End)
                  .Title("Окончание")
                  .Format("{0:dd.MM.yyyy HH:mm}")
                  .Width(120);
              columns.Template(@<text></text>)
                  .ClientTemplate("#=" + "templateButtonEvent".jsKendoTemplate() + "#")
                  .Width(85);
          }).Sortable().DataSource(ds =>
          {
              ds.Ajax()
                  .ServerOperation(false)
                  .Read(act =>
                  {
                      act.Action("Read", "Plan", new
                      {
                          area = "GlobalEvents"
                      })
                          .Data("GridReadData");
                  });
          }))
    </div>
</div>

FX2/WebGBFXT/Areas/GlobalEvents/Views/Plan/Table.cshtml
@using System.Globalization
@using System.Threading
@using Finflaex.Support.Reflection
@using Finflaex.Support.Telerik
@using Finflaex.Support.Types
@using Kendo.Mvc.UI
@using WebGBFXT.Areas.GlobalEvents.Controllers
@model IEnumerable<WebGBFXT.Areas.GlobalEvents.Controllers.PlanController.TableEventModelItem>

@{
    ViewBag.Title = "Мероприятия";
    Layout = "~/Views/Shared/_OneIndex.cshtml";
}

<script id="templateButtonOrg" type="text/x-kendo-template">
    <a class='btn btn-sm btn-default' href='Organization/Card?id=#:ID#'><i class='fa fa-list'></i></a>
</script>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        @{
            var data = ViewData["info"].AsType<PlanController.TableEventModel>();
            Thread.CurrentThread.CurrentCulture = new CultureInfo("ru-RU");
            if (data._Start == null)
            {
                data._Start = DateTimeOffset.Now;
            }
            if (data._End == null)
            {
                data._End = data._Start;
            }
        }
        <h2>@data.Caption</h2>
        <small>@data.Departament</small>
        <div>
            <strong>с @data._Start.Value.ToString("dd MMMM yyyy г.") по @data._End.Value.ToString("dd MMMM yyyy г.")</strong>
        </div>
        <p>@Html.Raw(data.Comment)</p>
    </div>
</div>

<div class="wrapper wrapper-content">
    <div class="animated fadeIn">
        @(Html.Kendo().Grid(Model).Name("PlanOrgTable")
              .Columns(columns =>
              {
                  columns
                      .Bound(v => v.OrgName)
                      .Title("Наименование");
                  columns
                      .Bound(v => v.OrgAddress)
                      .Title("Адрес");
                  columns.Template(@<text>
                                       <a class='btn btn-sm btn-default' href='@Url.FullUrl("Organization", "Card", "Index", new fxcDictSO().Set("id", item.ID))'>
                                           <i class='fa fa-list'></i>
                                       </a>
                                    </text>)
                      .ClientTemplate("templateButtonOrg".jsKendoTemplate())
                      .Width(40);
              }).Sortable()
              )
    </div>
</div>