FX2/WebGBFXT/Areas/Seminar/Controllers/InviteController.cs
#region

using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using BaseDBFX.Base;
using BaseDBFX.Models;
using BaseDBFX.Table;
using Finflaex.Support.MVC.Models;
using Finflaex.Support.Reflection;

#endregion

namespace WebGBFXT.Areas.Seminar.Controllers
{
    /// <summary>
    /// Таблица могущих прийти на семинар
    /// </summary>
    public class InviteController : Controller
    {
        /// <summary>
        /// Получение представления
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> Index(Guid? id)
            => await this.func(gb =>
            {
                if (id == null)
                    return RedirectToAction("Index", "List", new
                        {
                            area = "Seminar"
                        })
                        .AsType<ActionResult>();
                gb.GuidValue = new MainValue
                {
                    id = id.Value
                };
                return View(gb);
            });

        /// <summary>
        /// Сохранение пользовательских настроек
        /// </summary>
        /// <param name="id"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> SaveConfigLabels(
            Guid? id,
            SeminarInviteConfig model)
            => await this.func(gb =>
            {
                var query =
                    from user in gb.db.Logins
                    where user.ID == gb.AuthorGuid
                    select new
                    {
                        user,
                        file = user.Files
                            .Where(file => file.Type == TypeFile.Config)
                            .FirstOrDefault(file => file.Name == Login.Configs.SeminarInviteConfig)
                    };

                var read = query.First();

                if (read.file == null)
                    read.user.Files.Add(new RawFile
                    {
                        Raw = model.AsBytes(),
                        Type = TypeFile.Config,
                        Name = Login.Configs.SeminarInviteConfig
                    });
                else
                    read.file.Raw = model.AsBytes();
                gb.Save();

                if (id == null)
                    return RedirectToAction("Index", "List", new
                        {
                            area = "Seminar"
                        })
                        .AsType<ActionResult>();
                gb.GuidValue = new MainValue
                {
                    id = id.Value
                };
                return View("Table", gb);
            });

        /// <summary>
        /// Приглашение
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> WillCome(
            WillComeModel model)
            => await this.json(gb =>
            {
                var read = (
                        from seminar in gb.db.Events
                        where seminar.ID == model.seminar
                        from org in gb.db.Organizations
                        where org.ID == model.organization
                        from e in org.Events
                        where e.Type == EventType.progress
                        where !e.Closed
                        where e.Start < gb.Now
                        where e.End > gb.Now
                        select new
                        {
                            e.Users,
                            seminar
                        }
                    )
                    .FirstOrDefault();

                var start = model
                    .datetime
                    .ToDateTime("dd.MM.yyyy HH:mm", DateTime.Now)
                    .ToTZDateTimeOffset(gb.TimeZone);

                gb.db.Events.Add(new Event
                {
                    OrgID = model.organization,
                    RecordID = model.record,
                    Prev = read.seminar,
                    Users = read.Users,
                    Start = start,
                    Description = model.comment,
                    Type = model.flag == 1
                        ? EventType.seminarPromised
                        : model.flag == 2
                            ? EventType.seminarCanceled
                            : EventType.callSeminar
                });

                gb.Save();

                return new {OK = true};

                //return new
                //{
                //    message = "<a class='btn btn-danger fa fa-close' onclick='popUpClose()'></a> данные не обработаны"
                //};
            });

        public class WillComeModel
        {
            public Guid seminar { get; set; }
            public Guid organization { get; set; }
            public Guid record { get; set; }
            public string comment { get; set; }
            public int flag { get; set; }
            public string datetime { get; set; }
        }
    }
}

FX2/WebGBFXT/Areas/Seminar/Views/Invite/Index.cshtml
@using BaseDBFX.Models
@using BaseDBFX.Table
@using Finflaex.Support.Reflection
@model BaseDBFX.Base.ActionData

@{
    ViewBag.Title = "План обзвона на семинар";
    Layout = "~/Views/Shared/_WithOutKendo.cshtml";

    var db = Model.db;

    var filter = (
        from user in db.Logins
        where user.ID == Model.AuthorGuid
        from file in user.Files
        where file.Type == TypeFile.Config
        where file.Name == Login.Configs.SeminarInviteConfig
        select file)
        .FirstOrDefault()
        .retIfNull(new RawFile {Raw = new byte[0]})
        .FuncSelect(raw => raw.Raw.AsObject<SeminarInviteConfig>())
        .retIfNull(new SeminarInviteConfig());

    var label_contains = filter.Contains ?? new Guid[0];
    var label_not_contains = filter.NotContains ?? new Guid[0];
}

@section head
{
    <link href="~/Content/bootstrap-select.min.css" rel="stylesheet"/>

    @*<link href="~/Content/bootstrap-datetimepicker.css" rel="stylesheet"/>
    <script src="~/Scripts/bootstrap-datetimepicker.js"></script>*@

    @*http://eonasdan.github.io/bootstrap-datetimepicker/*@
    <link rel="stylesheet prefetch" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.3/css/bootstrap-datetimepicker.min.css">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>

    <script src="~/Scripts/jquery.tmpl.js"></script>
}
@section script
{
    <script src="~/Scripts/bootstrap-select.min.js"></script>
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        @{
            var seminar = db.Events.Where(v => v.ID == Model.GuidValue.id).Select(v => new
            {
                v.Prev.Prev.Caption,
                v.Start,
                v.End,
                desc1 = v.Prev.Prev.Description,
                desc2 = v.Prev.Description,
                desc3 = v.Description,
                TimeZone = v.Prev.Address.Where(a => a.Type == AddressType.region).Select(a => a.TimeZone).FirstOrDefault(),
                Address = v.Prev.Address.OrderBy(a => a.Type).Select(a => a.Suffix + " " + a.Name)
            })
                .FirstOrDefault();

            var start_date = seminar.Start.ToTZString(seminar.TimeZone);
            var end_date = seminar.End.ToTZString(seminar.TimeZone);
        }
        <ol class="breadcrumb">
            <li>
                <a class="btn btn-link" href="@Url.Action("Index", "List", new {area = "Seminar"})">
                    Список семинаров
                </a>
            </li>
            <li>
                <a class="btn btn-link" href="@Url.Action("Index", "Invited", new {area = "Seminar"})">
                    <strong>
                        @ViewBag.Title
                    </strong>
                </a>
            </li>
        </ol>
        <h2>@seminar.Caption</h2>
        <div>@seminar.Address.Join(", ")</div>
        <div>с: @start_date</div>
        <div>по: @end_date</div>
        <small>@Html.Raw(seminar.desc1)</small>
        <small>@Html.Raw(seminar.desc2)</small>
        <small>@Html.Raw(seminar.desc3)</small>
    </div>
</div>

<div class="wrapper wrapper-content">
    <div class="ibox float-e-margins border-bottom">
        <div class="ibox-title collapse-link" style="cursor: pointer" id="filter_opener">
            <h5>Настройки фильтрации</h5>
        </div>
        <div class="ibox-content">
            <div id="filter_table">
                @{
                    var query_labels =
                        from label in db.Labels
                        where label.Type != TypeLabel.user || label.User.ID == db.AuthorID
                        select new
                        {
                            label.ID,
                            label.Caption
                        };

                    <div class="form-group">
                        <label>Содержит метки:</label>
                        <select id="filter_contains" class="selectpicker form-control" data-live-search="true" multiple="multiple" data-width="100%">
                            @foreach (var label in query_labels)
                            {
                                <option value="@label.ID"
                                        @(label_contains.Contains(label.ID) ? "selected" : string.Empty)>
                                    @label.Caption
                                </option>
                            }
                        </select>
                    </div>

                    <div class="form-group">
                        <label>Не содержит метки:</label>
                        <select id="filter_not_contains" class="selectpicker form-control" data-live-search="true" multiple="multiple" data-width="100%">
                            @foreach (var label in query_labels)
                            {
                                <option value="@label.ID"
                                        @(label_not_contains.Contains(label.ID) ? "selected" : string.Empty)>
                                    @label.Caption
                                </option>
                            }
                        </select>
                    </div>
                }
            </div>
        </div>
    </div>

    <script>
        $('#filter_contains, #filter_not_contains').on('hidden.bs.select',
            function(e) {
                save_list_config();
            });

        function save_list_config() {
            $('#content_table').html('<h1>Загрузка ...</h1>');

            $.ajax({
                type: 'post',
                url: '@Url.Action("SaveConfigLabels", "Invite", new {area = "Seminar", Model.GuidValue.id})',
                dataType: 'html',
                contentType: 'application/json',
                data: JSON.stringify({
                    Contains: $('#filter_contains').val(),
                    NotContains: $('#filter_not_contains').val(),
                }),
                complete: function(read) {
                    $('#content_table').html(read.responseText);
                }
            });
        }
    </script>

    <div class="ibox">
        <div class="ibox-content" id="content_table">
            @{
                Html.RenderPartial("Table", Model);
            }
        </div>
    </div>
</div>

FX2/WebGBFXT/Areas/Seminar/Views/Invite/Table.cshtml
@using BaseDBFX.Models
@using BaseDBFX.Table
@using Finflaex.Support.Reflection
@model BaseDBFX.Base.ActionData

@{
    Layout = null;

    var db = Model.db;

    var filter = (
        from user in db.Logins
        where user.ID == Model.AuthorGuid
        from file in user.Files
        where file.Type == TypeFile.Config
        where file.Name == Login.Configs.SeminarInviteConfig
        select file)
        .FirstOrDefault()
        .retIfNull(new RawFile {Raw = new byte[0]})
        .FuncSelect(raw => raw.Raw.AsObject<SeminarInviteConfig>())
        .retIfNull(new SeminarInviteConfig());

    var label_contains = filter.Contains ?? new Guid[0];
    var label_not_contains = filter.NotContains ?? new Guid[0];

    var has_contains = !label_contains.Any();
    var has_not_contains = !label_not_contains.Any();

    var read_orgs = (
        from seminar in db.Events
        where seminar.ID == Model.GuidValue.id
        let adr = (
            from adr in seminar.Prev.Address
            orderby adr.Type descending
            select adr
            )
            .FirstOrDefault()
        from org in adr.Organizations
        let progress = (
            from e in org.Events
            where !e.Closed
            where e.Start < db.Now
            where e.End > db.Now
            where e.Type == EventType.progress
            select e
            )
        where progress.SelectMany(v => v.Users).Any(v => v.ID == db.AuthorID)
        where has_contains || org.Labels.Any(v => label_contains.Contains(v.ID))
        where has_not_contains || org.Labels.All(v => !label_not_contains.Contains(v.ID))
        let records = (
            from rec in org.Contacts
            where seminar.Next.Where(v => !v.Closed).All(v => v.RecordID != rec.ID)
            where rec.Contacts.Any(v => v.Type == ContactType.phone)
            select new
            {
                rec.ID,
                FIO = rec.Persons.Select(v => v.FullName).FirstOrDefault(),
                Phones = rec.Contacts.Where(v => v.Type == ContactType.phone).Select(v => v.ParseValue),
                Posts = rec.Posts.Select(v => v.Caption)
            }
            )
        where records.Any()
        select new
        {
            org.ID,
            Name = org.ShortName ?? org.FullName,
            Address = org.FormatAddress ?? org.PhysicalAdress ?? org.LegalAddress,
            Records = records
        })
        .ToArray();

    foreach (var org in read_orgs)
    {
        <div class="row border-bottom" id="@org.ID">
            <div class="col-md-8">
                <a class="btn btn-link" href="@Url.Action("Index", "Card", new {area = "Organization", id = org.ID})" target="_blank">@org.Name</a>
                <div class="small m-b-xs">@org.Address</div>
                @foreach (var rec in org.Records)
                {
                    <dl style="margin-left: 20px;" id="@rec.ID">
                        <dt>@rec.FIO</dt>
                        <dd>
                            <div>@rec.Posts.Join(", ")</div>
                            <div>
                                <a class="btn btn-primary btn-xs willCome"
                                   data-seminar="@Model.GuidValue.id"
                                   data-org="@org.ID"
                                   data-rec="@rec.ID"
                                   data-flag="1">
                                    придёт
                                </a>
                                <a class="btn btn-danger btn-xs notWillCome"
                                   data-seminar="@Model.GuidValue.id"
                                   data-org="@org.ID"
                                   data-rec="@rec.ID"
                                   data-flag="2">
                                    не придёт
                                </a>
                                <a class="btn btn-success btn-xs inviteTask"
                                   data-seminar="@Model.GuidValue.id"
                                   data-org="@org.ID"
                                   data-rec="@rec.ID"
                                   data-flag="3">
                                    напоминалка
                                </a>
                                @foreach (var phone in rec.Phones)
                                {
                                    <a class="btn btn-info btn-xs"
                                       style="font-size: 1.1em;"
                                       onclick="copyToClipboard(this)"
                                       data-phone="@phone">
                                        <strong>
                                            @string.Format("{0:# (###) ###-##-##}", phone.Prepend("8").ToLong())
                                        </strong>
                                    </a>
                                }
                            </div>
                        </dd>
                    </dl>
                }
            </div>
            <div class="col-md-4">

            </div>
        </div>
    }
}

<script id="will_come" type="text/x-jquery-tmpl">
    <form role="form" id="willComeForm">
        <input type="hidden" class="seminar" value="${seminar}"/>
        <input type="hidden" class="organization" value="${org}"/>
        <input type="hidden" class="record" value="${rec}"/>
        <input type="hidden" class="flag" value="${flag}"/>
        <div class="form-group">
            <label>Комментарий</label>
            <textarea class="form-control comment" rows="5"></textarea>
        </div>
        <div class="form-group">
            <button class="btn btn-sm btn-danger" type="button" onclick="$('#popup').hide()">
                <strong>Отменить</strong>
            </button>
            {{if flag == 1}}
            <input class="btn btn-sm btn-primary pull-right" type="submit" value="Придёт"/>
            {{else}}
            <input class="btn btn-sm btn-success pull-right" type="submit" value="Не придет"/>
            {{/if}}
        </div>
    </form>
</script>

<script id="invite_task" type="text/x-jquery-tmpl">
    <form role="form" id="willComeForm">
        <input type="hidden" class="seminar" value="${seminar}"/>
        <input type="hidden" class="organization" value="${org}"/>
        <input type="hidden" class="record" value="${rec}"/>
        <input type="hidden" class="flag" value="${flag}"/>
        <div class="form-group">
            <label>Дата напоминания</label>
            <input type="text" class="form-control datetime" value="@DateTime.Now.AddHours(1).ToString("dd.MM.yyyy HH:mm")"/>
        </div>
        <div class="form-group">
            <label>Комментарий</label>
            <textarea class="form-control comment" rows="5"></textarea>
        </div>
        <div class="form-group">
            <button class="btn btn-sm btn-danger" type="button" onclick="$('#popup').hide()">
                <strong>Отменить</strong>
            </button>
            <input class="btn btn-sm btn-success pull-right" type="submit" value="Напомнить"/>
        </div>
    </form>
</script>

<script>
    function copyToClipboard(el) {

        const aux = document.createElement("input");
        const value = $(el).data('phone');
        aux.setAttribute("value", `98${value}`);
        document.body.appendChild(aux);
        aux.select();
        document.execCommand("copy");

        document.body.removeChild(aux);
    }

    $(document)
        .on('click',
            '.willCome, .notWillCome',
            function(e) {
                const data = $(this).data();

                const tpl = $('#will_come').tmpl(data);
                $('#popup_content').html(tpl);
                $('#popup').show();
            })
        .on('click',
            '.inviteTask',
            function(e) {
                const data = $(this).data();

                const tpl = $('#invite_task').tmpl(data);
                tpl.find('.datetime').datetimepicker({
                    locale: 'ru-RU'
                });
                $('#popup_content').html(tpl);
                $('#popup').show();
            })
        .on('submit',
            '#willComeForm',
            function(e) {
                e.preventDefault();

                $('#willComeForm [type="submit"], #willComeForm [type="button"]').attr('disabled', true);

                var data = {
                    seminar: $('#willComeForm .seminar').val(),
                    organization: $('#willComeForm .organization').val(),
                    record: $('#willComeForm .record').val(),
                    comment: $('#willComeForm .comment').val(),
                    flag: $('#willComeForm .flag').val(),
                    datetime: $('#willComeForm .datetime').val()
                };

                jQuery
                    .ajax({
                        url: '@Url.Action("WillCome", "Invite", new {area = "Seminar"})',
                        contentType: 'application/json',
                        dataType: 'json',
                        type: 'post',
                        data: JSON.stringify(data)
                    })
                    .always(function() {
                        $('#willComeForm [type="submit"], #willComeForm [type="button"]').attr('disabled', false);
                    })
                    .done(function(e) {
                        if (e.OK) {
                            $(`#${data.record}`).remove();
                            if (!$(`#${data.organization} dl`).length) {
                                $(`#${data.organization}`).remove();
                            }
                            $('#popup').hide();
                        } else {
                            $('#popup_content').html(e.message);
                        }
                    });

                return false;
            });
</script>